# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0002_auto_20160918_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.BigIntegerField(db_index=True)),
                ('end_location', models.BigIntegerField(db_index=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedChord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ticks', models.IntegerField(db_index=True)),
                ('delay', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.Play')),
            ],
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
