# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0003_auto_20161028_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='play',
            name='start_location',
        ),
    ]
