// console.log('eb', whiteKeysDistance(75) === -1)
// console.log('e', whiteKeysDistance(76) === -1)
// console.log('f', whiteKeysDistance(77) === 0)
// console.log('gb', whiteKeysDistance(78) === 1)
// console.log('g', whiteKeysDistance(79) === 1)
// console.log('ab', whiteKeysDistance(80) === 2)
// console.log('a', whiteKeysDistance(81) === 2)
// console.log('bb', whiteKeysDistance(82) === 3)
// console.log('b', whiteKeysDistance(83) === 3)
// console.log('c', whiteKeysDistance(84) === 4)
// console.log('db', whiteKeysDistance(85) === 5)
// console.log('d', whiteKeysDistance(86) === 5)
// console.log('eb', whiteKeysDistance(87) === 6)
// console.log('e', whiteKeysDistance(88) === 6)
// console.log('f', whiteKeysDistance(89) === 7)
// console.log('gb', whiteKeysDistance(90) === 8)
// console.log('g', whiteKeysDistance(91) === 8)
// console.log('ab', whiteKeysDistance(92) === 9)
// console.log('a', whiteKeysDistance(93) === 9)
// console.log('bb', whiteKeysDistance(94) ===10)
// console.log('b', whiteKeysDistance(95) ===10)
// console.log('c', whiteKeysDistance(96) ===11)
// console.log('db', whiteKeysDistance(97) ===12)
// console.log('d', whiteKeysDistance(98) ===12)
// console.log('eb', whiteKeysDistance(99) ===13)
// console.log('e', whiteKeysDistance(100) ===13)
